version: "3"
networks:
  default:
    name: "mqtt-network"

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    user: mosquitto
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config
      - ./log:/mosquitto/log
      - ./data:/mosquitto/data
      #
      # - ./log:/mosquitto/log:rw
  # mqtt-pub:
  #   image: eclipse-mosquitto:latest
  #   command: sh -c "mosquitto_pub -h mqtt-broker -t test -m 'Hello World' -u admin -P password"
  #   depends_on:
  #     - mqtt-broker
  #   networks:
  #     mqtt-net:
  #       ipv4_address: 172.100.10.11
  # mqtt-sub:
  #   image: eclipse-mosquitto:latest
  #   command: sh -c "mosquitto_sub -h mqtt-broker -t test -u admin -P password"
  #   depends_on:
  #     - mqtt-broker
  #   networks:
  #     mqtt-net:
  #       ipv4_address: 172.100.10.12
volumes:
  config:
    name: "mqtt-broker-config"
  data:
    name: "mqtt-broker-data"
  log:
    name: "mqtt-broker-log"
